{% set name = "adani" %}
{% set version = "1.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/adani-{{ version }}.tar.gz
  sha256: 412ef18e708b5a73b73339fbe68be642f881778eeb7a202b368f91499b279a74

build:
  skip: true  # [win]
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - pybind11                               # [build_platform != target_platform]
    - pkg-config                             # [build_platform != target_platform]
    - {{ compiler("cxx") }}
    - {{ compiler("fortran") }}
    - {{ stdlib("c") }}
    - cmake >=3.15
    - make
  host:
    - python
    - pip
    - pybind11 >=2.9.2
    - scikit-build
    - versioneer ==0.29
    - gsl >=2.8
    - libblas
    - setuptools
  run:
    - python

test:
  imports:
    - adani
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/niclaurenti/adani
  summary: Code computing approximate DIS N3LO coefficients
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE

extra:
  recipe-maintainers:
    - niclaurenti
