{% set name = "adani" %}
{% set version = "1.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/adani-{{ version }}.tar.gz
  sha256: 21d408317abe2b438a6c15d6eeaff046324eb02fc7c37f8cc489ac3261e43881

build:
  skip: True  # [win]
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - {{ compiler("cxx") }}
    - {{ compiler("fortran") }}
    - cmake >=3.15
    - make
  host:
    - python
    - pip
    - pybind11 >=2.9.2
    - scikit-build
    - versioneer ==0.29
    - gsl >=2.7
    - libblas
  run:
    - python

test:
  imports:
    - adani
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/niclaurenti/adani
  summary: Code computing approximate DIS N3LO coefficients
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE

extra:
  recipe-maintainers:
    - niclaurenti
